---
- name: Provision digital ocean droplets
  hosts: localhost
  gather_facts: false
  vars_files:
    - instances.yml

  tasks:
    - include: tasks/digitalocean.yml

- name: initialize nodes
  hosts: nodes
  user: root
  gather_facts: false

  roles:
    - common

