---
- name: Provision digital ocean droplets
  hosts: localhost
  gather_facts: false
  vars_files:
    - instances.yml

  tasks:
    - include_tasks: provisioners/digitalocean.yml

- name: Add deploy user to new instances
  hosts: new-nodes
  user: root
  gather_facts: false
  vars_files:
    - instances.yml

  tasks:
    - import_tasks: provisioners/adduser.yml


